version: '3.1'

services:
  frontend:
    image: dependifyui:latest
    ports:
      - 3000:3000
    networks:
      - dependify
    
  backend:
    image: dependifyapi:latest
    ports:
      - 8000:8000
    networks:
      - dependify

networks:
  dependify:
    driver: bridge
