# Generated by Django 4.2 on 2023-06-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
                ('key', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('lastSync', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
