# Generated by Django 4.2 on 2023-06-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_newdatasource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
