name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build and push Docker image
        env:
          VERSION_FILE_PATH: 'version.txt' # Update with your version file path
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          VERSION=$(cat $VERSION_FILE_PATH)
          TAG=latest

          if [[ $VERSION != $TAG ]]; then
            TAG=$VERSION
          fi

          docker build -t your-docker-image:$TAG .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push your-docker-image:$TAG
